//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *DaemonSetItem) DeepCopyInto(out *DaemonSetItem) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new DaemonSetItem.
func (in *DaemonSetItem) DeepCopy() *DaemonSetItem {
	if in == nil {
		return nil
	}
	out := new(DaemonSetItem)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicDaemonSetDeployment) DeepCopyInto(out *SonicDaemonSetDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicDaemonSetDeployment.
func (in *SonicDaemonSetDeployment) DeepCopy() *SonicDaemonSetDeployment {
	if in == nil {
		return nil
	}
	out := new(SonicDaemonSetDeployment)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonicDaemonSetDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicDaemonSetDeploymentList) DeepCopyInto(out *SonicDaemonSetDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SonicDaemonSetDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicDaemonSetDeploymentList.
func (in *SonicDaemonSetDeploymentList) DeepCopy() *SonicDaemonSetDeploymentList {
	if in == nil {
		return nil
	}
	out := new(SonicDaemonSetDeploymentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *SonicDaemonSetDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicDaemonSetDeploymentSpec) DeepCopyInto(out *SonicDaemonSetDeploymentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicDaemonSetDeploymentSpec.
func (in *SonicDaemonSetDeploymentSpec) DeepCopy() *SonicDaemonSetDeploymentSpec {
	if in == nil {
		return nil
	}
	out := new(SonicDaemonSetDeploymentSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *SonicDaemonSetDeploymentStatus) DeepCopyInto(out *SonicDaemonSetDeploymentStatus) {
	*out = *in
	if in.DaemonsetList != nil {
		in, out := &in.DaemonsetList, &out.DaemonsetList
		*out = make([]DaemonSetItem, len(*in))
		copy(*out, *in)
	}
	if in.UpdateInProgressDaemonsetList != nil {
		in, out := &in.UpdateInProgressDaemonsetList, &out.UpdateInProgressDaemonsetList
		*out = make([]DaemonSetItem, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new SonicDaemonSetDeploymentStatus.
func (in *SonicDaemonSetDeploymentStatus) DeepCopy() *SonicDaemonSetDeploymentStatus {
	if in == nil {
		return nil
	}
	out := new(SonicDaemonSetDeploymentStatus)
	in.DeepCopyInto(out)
	return out
}
